### PR TITLE
Update ocnewsreader_sv.ts

### PR DESCRIPTION
**Pull request by eson57**
Translated

### CODE REVIEW

**Comment by buschmann23** [comment]
Thank you for the translation. I will add you to the list of contributors using the same data I used in Gibrievida, if it is ok. :)

**Comment by eson57** [comment]
Thanks, that's okay, I've also requested to join at Transifex, for maintaining translation.

**Comment by buschmann23** [comment]
I added you there. Somehow, Transifex did not send any notification about that.

**Comment by eson57** [comment]
OK, thanks!

**Pull request merged**
